Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -33,8 +33,19 @@ jobs:
       - uses: actions/checkout@v3
 
       # Runs a single command using the runners shell
-      - name: Debug
-        run: pwd && ls
+      - name: Checkout commit if provided
+        run: |
+          COMMIT="${{ github.events.inputs.commit }}"
+          if [[ -z "$COMMIT" ]]; then
+            echo "No commit provided, using head of main branch"
+          else
+            echo "Checkout commit $COMMIT"
+            if ! git checkout "$COMMIT"; then
+              echo "Failed to checkout commit!"
+              exit 1
+            fi
+          fi
+          git status
 
       # Runs a set of commands using the runners shell
       - name: Run a multi-line script
